name: 'Build and deploy to Google Cloud Run'

on:
  push:
    branches: ["main"]
  
  pull_request:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm install
      - run: npm test

      - name: Account authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      
      - name: Configure Docker Authentication
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # - name: Build and Push Container
      #   run: docker build -t node-cicd:latest .
      # - name: push image
      #   # run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/node-cicd:latest
      #   run: docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-docker-repo/node-cicd:latest

      - name: Build Docker Image
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-docker-repo/node-cicd:latest
          docker build -t $IMAGE_NAME .

      - name: Push Docker Image
        run: |
          IMAGE_NAME=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-docker-repo/node-cicd:latest
          docker push $IMAGE_NAME

      # - name: Deploy to Cloud Run
      #   uses: 'google-github-actions/deploy-cloudrun@v2'
      #   with:
      #     image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-docker-repo/node-cicd
      #     service: 'ritesh-cloudrun-cicd'
      #     region: 'us-central1'