name: 'Build and deploy to Google Cloud Run'

on:
  push:
    branches: ["main"]
  
  pull_request:
    branches: ["main"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm install
      - run: npm test

      - name: Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      
      - name: Configure Docker Authentication
        run: gcloud auth configure-docker --quiet

      - name: Build and Push Container
        run: |
          IMAGE_NAME=gcr.io/${{ secrets.GCP_PROJECT_ID }}/ritesh-cloudrun-cicd
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
      
      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          image: 'gcr.io/${{ secrets.GCP_PROJECT_ID }}/ritesh-cloudrun-cicd'
          service: 'ritesh-cloudrun-cicd'
          region: 'us-central1'